config/routes.rb
Rails.application.routes.draw do
  root to: redirect("/bands")

  resource :session, only: [:create, :destroy, :new]
  resources :users, only: [:create, :new, :show] do
    get :activate, on: :collection
  end

  resources :bands do
    resources :albums, only: [:new]
  end

  resources :albums, only: [:create, :destroy, :edit, :show, :update] do
    resources :tracks, only: [:new]
  end

  resources :tracks, only: [:create, :destroy, :edit, :show, :update]

  resources :notes, only: [:create, :destroy]
end

app/models/album.rb
class Album < ActiveRecord::Base
  ALBUM_QUALITY = %w(live studio)
  validates :title, :band_id, presence: true
  validates :los, presence: true, inclusion: {in: ALBUM_QUALITY}

  belongs_to(
    :band,
    class_name: 'Band',
    foreign_key: :band_id
  )
  has_many(
    :tracks, dependent: :destroy,
    class_name: 'Track',
    foreign_key: :album_id
  )

end

app/models/band.rb
class Band < ActiveRecord::Base
  validates :name, presence: true

  has_many(
    :albums, dependent: :destroy,
    class_name: 'Album',
    foreign_key: :band_id
  )
end

app/models/note.rb
class Note < ActiveRecord::Base
  validates :content, :track_id, :user_id, presence: true

  belongs_to(
    :track,
    class_name: "Track",
    foreign_key: :track_id
  )

  belongs_to(
    :user,
    class_name: "User",
    foreign_key: :user_id
  )
end

app/models/track.rb
class Track < ActiveRecord::Base
  TRACK_QUALITY = %w(bonus regular)
  validates :title, :album_id, presence: true
  validates :bor, presence: true, inclusion: {in: TRACK_QUALITY}
  #lyrics is an option. So, not validating here.
  belongs_to(
    :album,
    class_name: 'Album',
    foreign_key: :album_id
  )

  has_many(
    :notes,
    class_name: "Note",
    foreign_key: :track_id
  )
end

app/models/user.rb
class User < ActiveRecord::Base
  validates :password_digest, presence: {message: "password cannot be blank"}
  validates :email, uniqueness: true, presence: true
  validates :session_token, uniqueness: true, presence: true
  after_initialize :ensure_session_token

  def self.generate_session_token
    token = SecureRandom.urlsafe_base64
  end

  def self.find_by_credentials(email, password)
    user = User.find_by_email(email)
    unless user.nil?
      if user.is_password?(password)
        user
      end
    end
  end

  def reset_session_token!
    self.session_token = User.generate_session_token
    @session_token = self.session_token
  end

  def ensure_session_token
    self.session_token ||= User.generate_session_token

  end

  def password=(password)
    @password = BCrypt::Password.create(password)
    self.password_digest = @password
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end


end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  before_action :login_permission

  def new
    @album = Album.new
    @bands = Band.all
    render :new
  end

  def create
    album = Album.new(album_params)
    album.save
    redirect_to album_url(album)
  end

  def show
    @album = Album.find_by_id(params[:id])
    @bands = Band.all
    render :show
  end

  def update
    @album = Album.find_by_id(params[:id])
    @bands = Band.all
    render :update
  end

  def index
    @albums = Album.all
    render :index
  end

  def destroy
    album = Album.find_by_id(params[:id])
    album.destroy!
    redirect_to bands_url
  end
  private

  def album_params
    params.require(:album).permit(:title, :band_id, :los)
  end

  def logged_in?

  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user, :login_permission, :logged_in?

  def current_user
    return nil unless session[:session_token]
    @current_user ||= User.find_by_session_token(session[:session_token])
  end

  def login!(user)
    @current_user = user
    session[:session_token] = user.session_token
  end

  def log_in_user!
    @current_user.reset_session_token!
    login!(@current_user)
  end

  def logged_in?
    return true unless @current_user.nil?
    false
  end

  def login_permission
      redirect_to new_session_url if current_user.nil?
  end

end

app/controllers/bands_controller.rb
class BandsController < ApplicationController
  before_action :login_permission

  def new
    @band = Band.new
    render :new
  end

  def create
    band = Band.new(band_params)
    band.save
    redirect_to band_url(band)
  end

  def show
    @band = Band.find_by_id(params[:id])
    @albums = @band.albums.order(:title)
    render :show
  end

  def index
    @bands = Band.all
    @bands.order(:name)
    render :index
  end

  def update
    @band = Band.find_by_id(params[:id])
    render :update
  end

  def destroy
    @band = Band.find_by_id(params[:id])
    @band.destroy!
    redirect_to bands_url
  end

  private
  def band_params
    params.require(:band).permit(:name)
  end
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action :login_permission

  def create
    @note = Note.new(note_params)
    @note.user_id = current_user.id
    @note.save

    redirect_to track_url(@note.track_id)
  end

  def destroy
    @note = Note.find(params[:id])
    if @note.user_id != current_user.id
      render text: "Can only destroy your own note", status: :forbidden
    else
      @note.destroy
      redirect_to track_url(@note.track_id)
    end
  end

  private
  def note_params
    params.require(:note).permit(:content, :track_id)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    render :new
  end

  def create
    user = User.find_by_credentials(
      params[:user][:email],
      params[:user][:password]
    )
    if logged_in?
      flash[:errors] = "already logged in"
    elsif user.nil?
      flash[:errors] = "email/password combination cannot be found"
    else
      login!(user)
      redirect_to bands_url
    end
  end

  def destroy
      current_user.reset_session_token!
      session[:session_token] = nil
      redirect_to new_session_url
  end


end

app/controllers/tracks_controller.rb
class TracksController < ApplicationController
  before_action :login_permission

  def new
    @track = Track.new
    @albums = Album.all
    render :new
  end

  def create
    track = Track.new(track_params)
    track.save
    redirect_to track_url(track)
  end

  def update
    @track = Track.find_by_id(params[:id])
    @albums = Album.all
    render :update
  end

  def show
    @track = Track.find_by_id(params[:id])
    @albums = Album.all
    render :show
  end

  def destroy
    track = Track.find_by_id(params[:id])
    track.destroy!
    redirect_to bands_url
  end

  private
  def track_param
    params.require(:track).permit(:title, :album_id, :bor, :lyrics )
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
    render :new
  end

  def create
    user = User.new(users_params)
    if user.save!
      login!(user)
      redirect_to bands_url
    else
      flash.now json: user.errors.full_messages
      redirect_to new_user_url
    end

  end


  private
  def users_params
    params.require(:user).permit(:email, :password)
  end
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def auth_token
    ("<input name='authenticity_token'
      value= #{form_authenticity_token}
      type='hidden'>").html_safe
  end
end

app/helpers/bands_helper.rb
module BandsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tracks_helper.rb
module TracksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/albums/_form.html.erb
<!DOCTYPE html>
<html>
  <body>
    <h1> <%= album.title %> </h1>
    <form action = "bands/:band_id/albums" method = "post">
      <%= auth_token %>
      <label for = "new-album-title">Album Title:</label>
      <input id = "new-album-title" type = "text" name = "album[title]">
    <% if album.persisted? %>
    <input type = "hidden" name = "_method" value = "patch" >
    <% end %>
    <br>
    <label for = band-names>Band:</label>
      <select id = band-names name = "album[band_id]">
      <% bands.each do |b| %>
      <option value = <%= b.id %> <% "selected" if album.band_id == b.id %>>
        <%= b.name %> </option>
        <% end %>
      </select>
      <br>

      <label> Live <input type = "radio" name = "album[los]" value = "live"
          <%= "checked" if album.los == "live" %>> </label>

      <label> Studio <input type = "radio" name = "album[los]" value = "studio"
            <%= "checked" if album.los == "studio" %>> </label>


      <br>
      <% if album.persisted? %>
        <input type = "submit" value = "Update Track">
      <% else %>
        <input type = "submit" value = "Submit Track">
      <% end %>

  </form>
  </body>
</html>

app/views/albums/index.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <h1>List of All Albums</h1>
    <ul>
      <% @albums.each do |a| %>
      <%= link_to "#{a.title}", album_url(a) %>
      <% end %>
    </ul>
  </body>
</html>

app/views/albums/new.html.erb
<!DOCTYPE html>
<html>
<%= render "albums/form", album: @album, bands: @bands%>
</html>

app/views/albums/show.html.erb
<html>

<h1> <%= @album.title %></h1>
<h2> by <%= @album.band.name %></h2>
  <%= link_to "Look Up This Band", band_url(@album.band) %>
<br>
<h3>Tracks: </h3>
  <ol>
    <% @album.tracks.each do |t| %>
      <li><%= link_to "#{t.title}", track_url(t) %></li>
    <% end %>
    <br>
    <br>
    <%= link_to "Add a New Track To This Album", new_album_track_url(@album) %>
  </ol>
  <br>
<br>
  <%= button_to('Delete Album', album_url(@album),
          method: "delete", remote: true, data: { confirm: 'Are you sure?', disable_with: 'loading...' }) %>

</html>

app/views/albums/update.html.erb
<!DOCTYPE html>
<html>
<%= render "albums/form", album: @album, bands: @bands%>
</html>

app/views/bands/_form.html.erb
<!DOCTYPE html>
<html>
  <body>
  <form action = "/bands" method = "post">
    <%= auth_token %>
    <% if band.persisted? %>
    <h1> Update <%= band.name.upcase %> </h1>
    <input type = "hidden" name = "_method" value = "patch" >
    <% else %>
    <h1> Submit a Band </h1>
    <% end %>

    <label for = band-name>Band Name</label>
      <input type = "text" name = "band[name]"
      value = <%= "#{band.name}" if band.persisted?  %>>
      <br>

      <% if band.persisted? %>
        <input type = "submit" value = "Update Track">
      <% else %>
        <input type = "submit" value = "Submit Track">
      <% end %>

  </form>
  </body>
</html>

app/views/bands/index.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <h1>List of All Bands</h1>
    <ul>
      <% @bands.each do |b| %>
      <li><%= link_to "#{b.name}", band_url(b) %> </li>
      <% end %>
    </ul>
    <br>

    <%= button_to "Submit a New Band", new_band_url %>
  </body>
</html>

app/views/bands/new.html.erb
<!DOCTYPE html>
<html>
<%= render "bands/form", band: @band%>
</html>

app/views/bands/show.html.erb
<html>
<h1> <%= @band.name.upcase %></h1>
<h2> List of Albums: </h2>


<p>
  <ol>
    <% @band.albums.each do |a| %>
      <li><%= link_to "#{a.title}", album_url(a) %></li>
    <% end %>
  </ol>
  <%= link_to "Submit a New Album", new_band_album_url(@band) %>
</p>

<%= button_to('Delete This Band', band_url(@band),
        method: "delete", remote: true, data: { confirm: 'Are you sure?', disable_with: 'loading...' }) %>
</html>

app/views/bands/update.html.erb
<!DOCTYPE html>
<html>
<%= render "albums/form", album: @album, bands: @bands%>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MusicApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <% if logged_in? %>
    Hello, <%= @current_user.email %>
    <%= button_to 'Log Out', session_url, method: "delete" %>
  <% end %>

  <% if flash[:notice] %>
    <%= flash[:notice] %>
  <% end %>

  <%= yield %>
</body>
</html>

app/views/notes/_form.html.erb
<h2>New Note</h2>

<form action="<%= notes_url %>" method="POST">
  <input
    type="hidden"
    name="authenticity_token"
    value="<%= form_authenticity_token %>">

  <input type="hidden" name="note[track_id]" value="<%= track.id %>">

  <label for="note_content">Content</label>
  <br>

  <textarea id="note_content" name="note[content]"></textarea>
  <br>

  <input type="submit">
</form>

app/views/notes/_note.html.erb
<h3>Authored by: <%= note.user.email %></h3>
<ol><%= note.content %></ol>

<% if note.user_id == current_user.id %>
  <%= button_to "Destroy note!", note_url(note), method: :delete %>
<% end %>

app/views/tracks/_form.html.erb
<!DOCTYPE html>
<html>
  <body>
    <h1> <%= track.title %> </h1>
  <form action = "albums/:album_id/tracks" method = "post">
    <% if track.persisted? %>
    <input type = "hidden" name = "_method" value = "patch" >
    <% end %>
    <%= auth_token %>
    <label for = band-names>Album</label>
      <select id = band-names name = "track[album_id]">
      <% albums.each do |a| %>
      <option value = <%= a.id %> <% "selected" if track.album_id == a.id %>>
        <%= a.title %> </option>
        <% end %>
      </select>
      <br>

      <label> Bonus <input type = "radio" name = "track[bor]" value = "bonus"
          <%= "checked" if track.bor == "bonus" %>> </label>

      <label> Regular <input type = "radio" name = "album[bor]" value = "regular"
            <%= "checked" if track.bor == "regular" %>> </label>
      <br>

      <textarea name = "track[lyrics]" value = "Lyrics"><%=track.lyrics%></textarea>
      <br>

      <% if track.persisted? %>
        <input type = "submit" value = "Update Track">
      <% else %>
        <input type = "submit" value = "Submit Track">
      <% end %>

  </form>
  </body>
</html>

app/views/tracks/index.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <h1>List of All tracks</h1>
    <ul>
      <% @tracks.each do |a| %>
      <%= link_to "#{a.title}", track_url(a) %>
      <% end %>
    </ul>
  </body>
</html>

app/views/tracks/new.html.erb
<!DOCTYPE html>
<html>
<%= render "tracks/form", track: @track, albums: @albums%>
</html>

app/views/tracks/show.html.erb
<html>
<h1> <%= @track.title %></h1>
<h2> from <%= @track.album.title %></h2>
<%= link_to "Look Up Album", album_url(@track.album) %>
<h3>Track Type: <%= @track.bor %></h3>

<p>
  <h3>Lyrics: </h3>
  <%= @track.lyrics %>
</p>


<h3>Notes: </h3>
<% @track.notes.each do |note| %>
  <%= render "notes/note", note: note %>
<% end %>
<%= render "notes/form", track: @track %>

<br>
<%= button_to('Delete Track', track_url(@track),
  method: :delete) %>
</html>

app/views/tracks/update.html.erb
<!DOCTYPE html>
<html>
<%= render "tracks/form", track: @track, albums: @albums%>
</html>

app/views/users/new.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <h1>Welcome to Music App!</h1>
    <form action = "/users" method = "post">
      <%= auth_token %>
      <label for = "login-email">User Email: </label>
      <input id = "login-email"
        name = "user[email]", type = "text">

      <label for = "login-password">Password: </label>

      <input id = "login-password"
        name = "user[password]", type = "text">
      <br>

      <input type = "submit" value = "Create Account">
    </form>
    <br>
  </body>
</html>